### ISSUE TITLE
Error build with 6.1.135

### ISSUE THREAD

**Issue by ftoledo** [rhgndf/fl2000_drm#11]
Another try to build on debian 12 with linux 6.1.135:

ragnarok@ragnarok-pc:~/src/fl2000_drm-rhgndf$ make
make CHECK="/usr/bin/sparse" -C /lib/modules/6.1.0-34-amd64/build M=/home/ragnarok/src/fl2000_drm-rhgndf modules
make[1]: se entra en el directorio '/usr/src/linux-headers-6.1.0-34-amd64'
  CC [M]  /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_drv.o
  CC [M]  /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_registers.o
  CC [M]  /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_interrupt.o
  CC [M]  /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_streaming.o
  CC [M]  /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_connector.o
/home/ragnarok/src/fl2000_drm-rhgndf/fl2000_connector.c: In function ‘fl2000_get_modes’:
/home/ragnarok/src/fl2000_drm-rhgndf/fl2000_connector.c:35:15: error: implicit declaration of function ‘drm_edid_connector_add_modes’; did you mean ‘drm_edid_connector_update’? [-Werror=implicit-function-declaration]
   35 |         ret = drm_edid_connector_add_modes(connector);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               drm_edid_connector_update
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-34-common/scripts/Makefile.build:255: /home/ragnarok/src/fl2000_drm-rhgndf/fl2000_connector.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-34-common/Makefile:2038: /home/ragnarok/src/fl2000_drm-rhgndf] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-6.1.0-34-amd64'
make: *** [Makefile:18: modules] Error 2

**Comment by rhgndf** [comment]
Updated to latest kernel

**Comment by ftoledo** [comment]
hi @rhgndf do you check the https://github.com/ADCDS/fl2000drm.git fork?
this working for my with a usb-vga adapter
